"""asignaciones bancarias

Revision ID: asign_0004
Revises: cierre_0003
Create Date: 2026-10-01 22:48:57.184917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'asign_0004'
down_revision: Union[str, Sequence[str], None] = 'cierre_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('related_transaction_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['bank_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['bank_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_allocations_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_allocations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_allocations_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_allocations_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_bank_allocations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bank_allocations_invoice_id'))

    op.drop_table('bank_allocations')
    # ### end Alembic commands ###
