"""bancos conectados

Revision ID: banco_0005
Revises: asign_0004
Create Date: 2026-10-01 23:18:01.143986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'banco_0005'
down_revision: Union[str, Sequence[str], None] = 'asign_0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('requisition_id', sa.String(length=100), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accounts', sa.JSON(), nullable=False),
    sa.Column('consent_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_connections_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_bank_connections_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_connections_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bank_connections_reference'))

    op.drop_table('bank_connections')
    # ### end Alembic commands ###
