"""Esquema base: todas las tablas de CapaFiscal en el momento de adoptar Alembic.

Las bases creadas antes con create_all se completan y se marcan en esta versión (app/migrate.py).

Revision ID: base_0001
Revises: 
Create Date: 2026-10-01 17:18:33.455442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'base_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('automation_client_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_summary', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_automation_settings_tenant_code')
    )
    op.create_index(op.f('ix_automation_client_settings_tenant_id'), 'automation_client_settings', ['tenant_id'], unique=False)
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_runs_code'), 'automation_runs', ['code'], unique=False)
    op.create_index(op.f('ix_automation_runs_started_at'), 'automation_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_automation_runs_tenant_id'), 'automation_runs', ['tenant_id'], unique=False)
    op.create_table('bank_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('account_label', sa.String(length=100), nullable=True),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_duplicated', sa.Integer(), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_imports_tenant_id'), 'bank_imports', ['tenant_id'], unique=False)
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=30), nullable=True),
    sa.Column('legal_form', sa.String(length=20), nullable=True),
    sa.Column('activity', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hourly_cost', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('at_ep_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('invoice_footer', sa.Text(), nullable=True),
    sa.Column('default_payment_days', sa.Integer(), nullable=True),
    sa.Column('advisor_email', sa.String(length=255), nullable=True),
    sa.Column('late_interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profile_tenant_id'), 'company_profile', ['tenant_id'], unique=False)
    op.create_table('compliance_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_compliance_items_tenant_code')
    )
    op.create_index(op.f('ix_compliance_items_tenant_id'), 'compliance_items', ['tenant_id'], unique=False)
    op.create_table('counterparty_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'party', 'key', name='uq_counterparty_profile')
    )
    op.create_index(op.f('ix_counterparty_profiles_key'), 'counterparty_profiles', ['key'], unique=False)
    op.create_index(op.f('ix_counterparty_profiles_tenant_id'), 'counterparty_profiles', ['tenant_id'], unique=False)
    op.create_table('counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_counters_tenant_name')
    )
    op.create_index(op.f('ix_counters_tenant_id'), 'counters', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('payment_days', sa.Integer(), nullable=True),
    sa.Column('withholding_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_tax_id'), 'customers', ['tax_id'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('decision_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('predicted', sa.Text(), nullable=True),
    sa.Column('human', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('error_type', sa.String(length=40), nullable=True),
    sa.Column('engine', sa.String(length=30), nullable=True),
    sa.Column('subject_key', sa.String(length=150), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_created_at'), 'decision_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_records_document_id'), 'decision_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_decision_records_entity_type'), 'decision_records', ['entity_type'], unique=False)
    op.create_index(op.f('ix_decision_records_outcome'), 'decision_records', ['outcome'], unique=False)
    op.create_index(op.f('ix_decision_records_subject_key'), 'decision_records', ['subject_key'], unique=False)
    op.create_index(op.f('ix_decision_records_tenant_id'), 'decision_records', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_provider', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('extraction_status', sa.String(length=50), nullable=False),
    sa.Column('requires_ocr', sa.Boolean(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename'),
    sa.UniqueConstraint('tenant_id', 'sha256', name='uq_documents_tenant_sha256')
    )
    op.create_index(op.f('ix_documents_extraction_status'), 'documents', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_documents_is_demo'), 'documents', ['is_demo'], unique=False)
    op.create_index(op.f('ix_documents_kind'), 'documents', ['kind'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_index('ix_documents_source_external_id', 'documents', ['source', 'external_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('ss_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('contract_type', sa.String(length=30), nullable=False),
    sa.Column('workday_percent', sa.Integer(), nullable=False),
    sa.Column('annual_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payments_per_year', sa.Integer(), nullable=False),
    sa.Column('irpf_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('contribution_group', sa.Integer(), nullable=True),
    sa.Column('collective_agreement', sa.String(length=255), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('ss_status', sa.String(length=20), nullable=False),
    sa.Column('ss_registered_at', sa.Date(), nullable=True),
    sa.Column('ss_deregistered_at', sa.Date(), nullable=True),
    sa.Column('vacation_days', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_table('learning_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('subject_key', sa.String(length=150), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=True),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('simulation', sa.JSON(), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_rules_status'), 'learning_rules', ['status'], unique=False)
    op.create_index(op.f('ix_learning_rules_subject_key'), 'learning_rules', ['subject_key'], unique=False)
    op.create_index(op.f('ix_learning_rules_tenant_id'), 'learning_rules', ['tenant_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('to_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_entity', 'outbox_messages', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_kind'), 'outbox_messages', ['kind'], unique=False)
    op.create_index(op.f('ix_outbox_messages_status'), 'outbox_messages', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_messages_tenant_id'), 'outbox_messages', ['tenant_id'], unique=False)
    op.create_table('outlook_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('attachment_id', sa.String(length=512), nullable=False),
    sa.Column('attachment_name', sa.String(length=512), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'message_id', 'attachment_id', name='uq_outlook_tenant_message_attachment')
    )
    op.create_index(op.f('ix_outlook_imports_tenant_id'), 'outlook_imports', ['tenant_id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'year', 'month', name='uq_payroll_run_period')
    )
    op.create_index(op.f('ix_payroll_runs_tenant_id'), 'payroll_runs', ['tenant_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('supplier_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_id', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=False),
    sa.Column('learned_from_invoice_id', sa.Integer(), nullable=True),
    sa.Column('times_applied', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'tax_id', name='uq_supplier_rules_tenant_tax_id')
    )
    op.create_index(op.f('ix_supplier_rules_tax_id'), 'supplier_rules', ['tax_id'], unique=False)
    op.create_index(op.f('ix_supplier_rules_tenant_id'), 'supplier_rules', ['tenant_id'], unique=False)
    op.create_table('tax_filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'model', 'year', 'period', name='uq_tax_filings_model_period')
    )
    op.create_index(op.f('ix_tax_filings_tenant_id'), 'tax_filings', ['tenant_id'], unique=False)
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absences_employee_id'), 'absences', ['employee_id'], unique=False)
    op.create_index(op.f('ix_absences_start_date'), 'absences', ['start_date'], unique=False)
    op.create_index(op.f('ix_absences_tenant_id'), 'absences', ['tenant_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_employee_documents_employee_id'), 'employee_documents', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_documents_tenant_id'), 'employee_documents', ['tenant_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('extractor_name', sa.String(length=100), nullable=False),
    sa.Column('extractor_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_runs_document_id'), 'extraction_runs', ['document_id'], unique=False)
    op.create_index(op.f('ix_extraction_runs_tenant_id'), 'extraction_runs', ['tenant_id'], unique=False)
    op.create_table('fiscal_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('issuer', sa.String(length=30), nullable=False),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('debt', sa.JSON(), nullable=True),
    sa.Column('classification', sa.JSON(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('available_at', sa.Date(), nullable=True),
    sa.Column('notified_at', sa.Date(), nullable=True),
    sa.Column('deadline_term', sa.JSON(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('deadline_rule', sa.Text(), nullable=True),
    sa.Column('deadline_manual', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_notifications_deadline'), 'fiscal_notifications', ['deadline'], unique=False)
    op.create_index(op.f('ix_fiscal_notifications_document_id'), 'fiscal_notifications', ['document_id'], unique=True)
    op.create_index(op.f('ix_fiscal_notifications_status'), 'fiscal_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_fiscal_notifications_tenant_id'), 'fiscal_notifications', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_tax_id', sa.String(length=30), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_tax_id', sa.String(length=30), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('withholding_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('surcharge_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('concept', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('field_confidences', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('validation_messages', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('duplicate_status', sa.String(length=50), nullable=False),
    sa.Column('duplicate_of_invoice_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_direction'), 'invoices', ['direction'], unique=False)
    op.create_index(op.f('ix_invoices_document_id'), 'invoices', ['document_id'], unique=True)
    op.create_index(op.f('ix_invoices_duplicate_status'), 'invoices', ['duplicate_status'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_paid_at'), 'invoices', ['paid_at'], unique=False)
    op.create_index(op.f('ix_invoices_review_status'), 'invoices', ['review_status'], unique=False)
    op.create_index('ix_invoices_supplier_date_total', 'invoices', ['supplier_tax_id', 'invoice_date', 'total'], unique=False)
    op.create_index(op.f('ix_invoices_supplier_name'), 'invoices', ['supplier_name'], unique=False)
    op.create_index('ix_invoices_supplier_number', 'invoices', ['supplier_tax_id', 'invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_supplier_tax_id'), 'invoices', ['supplier_tax_id'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_invoices_validation_status'), 'invoices', ['validation_status'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('overtime', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('advance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contribution_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ss_employee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('irpf_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('irpf', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ss_employer', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('company_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_run_id'), 'payslips', ['run_id'], unique=False)
    op.create_index(op.f('ix_payslips_tenant_id'), 'payslips', ['tenant_id'], unique=False)
    op.create_table('project_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('allocation_percent', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'employee_id', name='uq_assignment_project_employee')
    )
    op.create_index(op.f('ix_project_assignments_employee_id'), 'project_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_project_assignments_project_id'), 'project_assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_assignments_tenant_id'), 'project_assignments', ['tenant_id'], unique=False)
    op.create_table('recurring_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('withholding_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('auto_issue', sa.Boolean(), nullable=False),
    sa.Column('auto_send', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_invoices_customer_id'), 'recurring_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recurring_invoices_tenant_id'), 'recurring_invoices', ['tenant_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('edit_reason', sa.String(length=255), nullable=True),
    sa.Column('edited_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_employee_id'), 'time_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_entries_tenant_id'), 'time_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_time_entries_work_date'), 'time_entries', ['work_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('api_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_sessions_token_hash'), 'api_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_sessions_user_id'), 'api_sessions', ['user_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('account_label', sa.String(length=100), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('matched_invoice_id', sa.Integer(), nullable=True),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['bank_imports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'fingerprint', name='uq_bank_transactions_tenant_fingerprint')
    )
    op.create_index(op.f('ix_bank_transactions_booking_date'), 'bank_transactions', ['booking_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_fingerprint'), 'bank_transactions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_bank_transactions_import_id'), 'bank_transactions', ['import_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_match_status'), 'bank_transactions', ['match_status'], unique=False)
    op.create_index(op.f('ix_bank_transactions_matched_invoice_id'), 'bank_transactions', ['matched_invoice_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_tenant_id'), 'bank_transactions', ['tenant_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('procedure', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('subject_type', sa.String(length=20), nullable=True),
    sa.Column('subject_name', sa.String(length=255), nullable=True),
    sa.Column('subject_tax_id', sa.String(length=30), nullable=True),
    sa.Column('subject_ref_id', sa.Integer(), nullable=True),
    sa.Column('organism', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('internal_deadline', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=False),
    sa.Column('proposed_actions', sa.JSON(), nullable=False),
    sa.Column('antecedents', sa.JSON(), nullable=False),
    sa.Column('draft_response', sa.Text(), nullable=True),
    sa.Column('draft_edited', sa.Boolean(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=120), nullable=True),
    sa.Column('filed_at', sa.Date(), nullable=True),
    sa.Column('filing_reference', sa.String(length=120), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notification_id'], ['fiscal_notifications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_cases_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'fingerprint', name='uq_cases_tenant_fingerprint')
    )
    op.create_index(op.f('ix_cases_code'), 'cases', ['code'], unique=False)
    op.create_index(op.f('ix_cases_deadline'), 'cases', ['deadline'], unique=False)
    op.create_index(op.f('ix_cases_fingerprint'), 'cases', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_cases_kind'), 'cases', ['kind'], unique=False)
    op.create_index(op.f('ix_cases_notification_id'), 'cases', ['notification_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_subject_tax_id'), 'cases', ['subject_tax_id'], unique=False)
    op.create_index(op.f('ix_cases_tenant_id'), 'cases', ['tenant_id'], unique=False)
    op.create_table('invoice_tax_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('tax_type', sa.String(length=30), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('tax_base', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_tax_lines_invoice_id'), 'invoice_tax_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_tax_lines_tenant_id'), 'invoice_tax_lines', ['tenant_id'], unique=False)
    op.create_table('sales_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=5), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_type', sa.String(length=5), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_snapshot', sa.JSON(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('operation_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('withholding_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('withholding_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('rectifies_id', sa.Integer(), nullable=True),
    sa.Column('rectification_reason', sa.String(length=255), nullable=True),
    sa.Column('recurring_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('record_timestamp', sa.String(length=40), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('qr_url', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rectifies_id'], ['sales_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recurring_id'], ['recurring_invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'series', 'year', 'number', name='uq_sales_invoice_number')
    )
    op.create_index(op.f('ix_sales_invoices_code'), 'sales_invoices', ['code'], unique=False)
    op.create_index(op.f('ix_sales_invoices_customer_id'), 'sales_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_invoices_recurring_id'), 'sales_invoices', ['recurring_id'], unique=False)
    op.create_index(op.f('ix_sales_invoices_status'), 'sales_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_sales_invoices_tenant_id'), 'sales_invoices', ['tenant_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('resolution', sa.String(length=100), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type', 'document_id', name='uq_tasks_type_document')
    )
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_document_id'), 'tasks', ['document_id'], unique=False)
    op.create_index('ix_tasks_inbox', 'tasks', ['status', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_invoice_id'), 'tasks', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_table('user_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_user_client')
    )
    op.create_index(op.f('ix_user_clients_client_id'), 'user_clients', ['client_id'], unique=False)
    op.create_index(op.f('ix_user_clients_user_id'), 'user_clients', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(length=40), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_case_id'), 'agent_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_pipeline'), 'agent_runs', ['pipeline'], unique=False)
    op.create_index(op.f('ix_agent_runs_started_at'), 'agent_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_tenant_id'), 'agent_runs', ['tenant_id'], unique=False)
    op.create_table('case_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=40), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_attachments_case_id'), 'case_attachments', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_attachments_tenant_id'), 'case_attachments', ['tenant_id'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_events_tenant_id'), 'case_events', ['tenant_id'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_action'), 'task_events', ['action'], unique=False)
    op.create_index(op.f('ix_task_events_created_at'), 'task_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_events_tenant_id'), 'task_events', ['tenant_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('engine', sa.String(length=60), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_steps_agent'), 'agent_steps', ['agent'], unique=False)
    op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_tenant_id'), 'agent_steps', ['tenant_id'], unique=False)
    op.create_table('document_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('to_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reminders_sent', sa.Integer(), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_reminder_at', sa.Date(), nullable=True),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['case_attachments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_requests_case_id'), 'document_requests', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_requests_status'), 'document_requests', ['status'], unique=False)
    op.create_index(op.f('ix_document_requests_tenant_id'), 'document_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_document_requests_token'), 'document_requests', ['token'], unique=True)
    op.create_table('ingested_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('failed_agent', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source', 'external_id', name='uq_ingested_event_source_external')
    )
    op.create_index(op.f('ix_ingested_events_case_id'), 'ingested_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_ingested_events_source'), 'ingested_events', ['source'], unique=False)
    op.create_index(op.f('ix_ingested_events_status'), 'ingested_events', ['status'], unique=False)
    op.create_index(op.f('ix_ingested_events_tenant_id'), 'ingested_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingested_events_tenant_id'), table_name='ingested_events')
    op.drop_index(op.f('ix_ingested_events_status'), table_name='ingested_events')
    op.drop_index(op.f('ix_ingested_events_source'), table_name='ingested_events')
    op.drop_index(op.f('ix_ingested_events_case_id'), table_name='ingested_events')
    op.drop_table('ingested_events')
    op.drop_index(op.f('ix_document_requests_token'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_tenant_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_status'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_case_id'), table_name='document_requests')
    op.drop_table('document_requests')
    op.drop_index(op.f('ix_agent_steps_tenant_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_run_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_agent'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_task_events_tenant_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_created_at'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_action'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_case_events_tenant_id'), table_name='case_events')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_case_attachments_tenant_id'), table_name='case_attachments')
    op.drop_index(op.f('ix_case_attachments_case_id'), table_name='case_attachments')
    op.drop_table('case_attachments')
    op.drop_index(op.f('ix_agent_runs_tenant_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_started_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_pipeline'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_case_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_user_clients_user_id'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_client_id'), table_name='user_clients')
    op.drop_table('user_clients')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_invoice_id'), table_name='tasks')
    op.drop_index('ix_tasks_inbox', table_name='tasks')
    op.drop_index(op.f('ix_tasks_document_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_sales_invoices_tenant_id'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_status'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_recurring_id'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_customer_id'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_code'), table_name='sales_invoices')
    op.drop_table('sales_invoices')
    op.drop_index(op.f('ix_invoice_tax_lines_tenant_id'), table_name='invoice_tax_lines')
    op.drop_index(op.f('ix_invoice_tax_lines_invoice_id'), table_name='invoice_tax_lines')
    op.drop_table('invoice_tax_lines')
    op.drop_index(op.f('ix_cases_tenant_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_subject_tax_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_notification_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_kind'), table_name='cases')
    op.drop_index(op.f('ix_cases_fingerprint'), table_name='cases')
    op.drop_index(op.f('ix_cases_deadline'), table_name='cases')
    op.drop_index(op.f('ix_cases_code'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_bank_transactions_tenant_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_matched_invoice_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_match_status'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_import_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_fingerprint'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_booking_date'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_api_sessions_user_id'), table_name='api_sessions')
    op.drop_index(op.f('ix_api_sessions_token_hash'), table_name='api_sessions')
    op.drop_table('api_sessions')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_time_entries_work_date'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_tenant_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_employee_id'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_recurring_invoices_tenant_id'), table_name='recurring_invoices')
    op.drop_index(op.f('ix_recurring_invoices_customer_id'), table_name='recurring_invoices')
    op.drop_table('recurring_invoices')
    op.drop_index(op.f('ix_project_assignments_tenant_id'), table_name='project_assignments')
    op.drop_index(op.f('ix_project_assignments_project_id'), table_name='project_assignments')
    op.drop_index(op.f('ix_project_assignments_employee_id'), table_name='project_assignments')
    op.drop_table('project_assignments')
    op.drop_index(op.f('ix_payslips_tenant_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_run_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_invoices_validation_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_supplier_tax_id'), table_name='invoices')
    op.drop_index('ix_invoices_supplier_number', table_name='invoices')
    op.drop_index(op.f('ix_invoices_supplier_name'), table_name='invoices')
    op.drop_index('ix_invoices_supplier_date_total', table_name='invoices')
    op.drop_index(op.f('ix_invoices_review_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_paid_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_duplicate_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_document_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_direction'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_fiscal_notifications_tenant_id'), table_name='fiscal_notifications')
    op.drop_index(op.f('ix_fiscal_notifications_status'), table_name='fiscal_notifications')
    op.drop_index(op.f('ix_fiscal_notifications_document_id'), table_name='fiscal_notifications')
    op.drop_index(op.f('ix_fiscal_notifications_deadline'), table_name='fiscal_notifications')
    op.drop_table('fiscal_notifications')
    op.drop_index(op.f('ix_extraction_runs_tenant_id'), table_name='extraction_runs')
    op.drop_index(op.f('ix_extraction_runs_document_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_employee_documents_tenant_id'), table_name='employee_documents')
    op.drop_index(op.f('ix_employee_documents_employee_id'), table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_absences_tenant_id'), table_name='absences')
    op.drop_index(op.f('ix_absences_start_date'), table_name='absences')
    op.drop_index(op.f('ix_absences_employee_id'), table_name='absences')
    op.drop_table('absences')
    op.drop_index(op.f('ix_tax_filings_tenant_id'), table_name='tax_filings')
    op.drop_table('tax_filings')
    op.drop_index(op.f('ix_supplier_rules_tenant_id'), table_name='supplier_rules')
    op.drop_index(op.f('ix_supplier_rules_tax_id'), table_name='supplier_rules')
    op.drop_table('supplier_rules')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_payroll_runs_tenant_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_outlook_imports_tenant_id'), table_name='outlook_imports')
    op.drop_table('outlook_imports')
    op.drop_index(op.f('ix_outbox_messages_tenant_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_status'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_kind'), table_name='outbox_messages')
    op.drop_index('ix_outbox_entity', table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_learning_rules_tenant_id'), table_name='learning_rules')
    op.drop_index(op.f('ix_learning_rules_subject_key'), table_name='learning_rules')
    op.drop_index(op.f('ix_learning_rules_status'), table_name='learning_rules')
    op.drop_table('learning_rules')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index('ix_documents_source_external_id', table_name='documents')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_kind'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_demo'), table_name='documents')
    op.drop_index(op.f('ix_documents_extraction_status'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_decision_records_tenant_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_subject_key'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_outcome'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_entity_type'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_document_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_created_at'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_tax_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_counters_tenant_id'), table_name='counters')
    op.drop_table('counters')
    op.drop_index(op.f('ix_counterparty_profiles_tenant_id'), table_name='counterparty_profiles')
    op.drop_index(op.f('ix_counterparty_profiles_key'), table_name='counterparty_profiles')
    op.drop_table('counterparty_profiles')
    op.drop_index(op.f('ix_compliance_items_tenant_id'), table_name='compliance_items')
    op.drop_table('compliance_items')
    op.drop_index(op.f('ix_company_profile_tenant_id'), table_name='company_profile')
    op.drop_table('company_profile')
    op.drop_index(op.f('ix_bank_imports_tenant_id'), table_name='bank_imports')
    op.drop_table('bank_imports')
    op.drop_index(op.f('ix_automation_runs_tenant_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_started_at'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_code'), table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index(op.f('ix_automation_client_settings_tenant_id'), table_name='automation_client_settings')
    op.drop_table('automation_client_settings')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
