"""cierre mensual

Revision ID: cierre_0003
Revises: inteligencia_0002
Create Date: 2026-10-01 20:32:31.066174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cierre_0003'
down_revision: Union[str, Sequence[str], None] = 'inteligencia_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_closes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=100), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'period', name='uq_period_closes_tenant_period')
    )
    with op.batch_alter_table('period_closes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_closes_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period_closes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_closes_tenant_id'))

    op.drop_table('period_closes')
    # ### end Alembic commands ###
