"""inteligencia: fuentes, elementos externos, relevancia y perfil

Revision ID: inteligencia_0002
Revises: base_0001
Create Date: 2026-10-01 17:42:31.605358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'inteligencia_0002'
down_revision: Union[str, Sequence[str], None] = 'base_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.String(length=80), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('xml_url', sa.String(length=500), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('detail_fetched', sa.Boolean(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'external_id', name='uq_external_items_source_id')
    )
    op.create_index(op.f('ix_external_items_publication_date'), 'external_items', ['publication_date'], unique=False)
    op.create_index(op.f('ix_external_items_source_code'), 'external_items', ['source_code'], unique=False)
    op.create_index(op.f('ix_external_items_type'), 'external_items', ['type'], unique=False)
    op.create_table('intel_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('intel_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('radar', sa.String(length=20), nullable=False),
    sa.Column('relevance', sa.String(length=10), nullable=False),
    sa.Column('areas', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profile_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['external_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'item_id', 'radar', name='uq_intel_matches_tenant_item_radar')
    )
    op.create_index(op.f('ix_intel_matches_item_id'), 'intel_matches', ['item_id'], unique=False)
    op.create_index(op.f('ix_intel_matches_radar'), 'intel_matches', ['radar'], unique=False)
    op.create_index(op.f('ix_intel_matches_tenant_id'), 'intel_matches', ['tenant_id'], unique=False)
    op.add_column('company_profile', sa.Column('intel_profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_profile', 'intel_profile')
    op.drop_index(op.f('ix_intel_matches_tenant_id'), table_name='intel_matches')
    op.drop_index(op.f('ix_intel_matches_radar'), table_name='intel_matches')
    op.drop_index(op.f('ix_intel_matches_item_id'), table_name='intel_matches')
    op.drop_table('intel_matches')
    op.drop_table('intel_sources')
    op.drop_index(op.f('ix_external_items_type'), table_name='external_items')
    op.drop_index(op.f('ix_external_items_source_code'), table_name='external_items')
    op.drop_index(op.f('ix_external_items_publication_date'), table_name='external_items')
    op.drop_table('external_items')
    # ### end Alembic commands ###
